language: go

go: 
 - 1.24.x
 - master

before_install:
 - go get github.com/mattn/goveralls

before_script: 
  - go vet ./...

script:
  - go test ./... -v -cover
  - $GOPATH/bin/goveralls -service=travis-ci
